{% set python_min = "3.8" %}
{% set name = "scgraph" %}
{% set version = "2.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scgraph-{{ version }}.tar.gz
  sha256: 40a778cb3e5224d5f0930698abba8ca17932e4ca1276d542eb64b9d741924cb7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - scgraph
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/connor-makowski/scgraph
  summary: Determine an approximate route between two points on earth
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vinisalazar