{% set python_min = "3.8" %}
{% set name = "scgraph" %}
{% set version = "3.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/scgraph-{{ version }}.tar.gz
  sha256: c863e9d19e8961c956cfcbceef860b5083038511d450eec46c8b03d3f6c343ed

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - scgraph
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/connor-makowski/scgraph
  summary: Determine an approximate route between two points on earth
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - vinisalazar
